// <auto-generated></auto-generated>
using System;
using ProtoBuf;

namespace SteamDatabaseBackend
{
    public class CChatRoom_SendChatMessage_Request : IExtensible
    {
        [ProtoMember(1, IsRequired = false, Name = "chat_group_id", DataFormat = DataFormat.Default)]
        public ulong chat_group_id { get; set; }

        [ProtoMember(2, IsRequired = false, Name = "chat_id", DataFormat = DataFormat.Default)]
        public ulong chat_id { get; set; }

        [ProtoMember(3, IsRequired = false, Name = "message", DataFormat = DataFormat.Default)]
        public string message { get; set; }

        private IExtension extensionObject;
        IExtension IExtensible.GetExtensionObject(bool createIfMissing) => Extensible.GetExtensionObject(ref extensionObject, createIfMissing);
    }
}
